x-common-env: &common-env
  SSL: "true"
  CERT_PATH: "/tls"
  REDIS_PASSWORD: "s3cr3t"

services:
  server-1:
    networks:
      - internal-net
      - frontend-net
    environment:
      <<: *common-env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./certs/redis-tls:/tls
    depends_on:
      redis:
        condition: service_healthy
  server-2:
    networks:
      - internal-net
      - frontend-net
    volumes:
      - ./certs/redis-tls:/tls
    environment:
      <<: *common-env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
  nginx:
    environment:
      SERVER_NAME: localhost
    image: nginx:latest
    networks:
      - frontend-net
    ports:
      - "9090:80"
      - "9091:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/https:/etc/nginx/ssl/
    depends_on:
      - server-1
      - server-2
  redis:
    environment:
      <<: *common-env
    image: local-redis-alpine
    ports:
      - "6379:6379"
    networks:
      - internal-net
    volumes:
      - ./redis_data:/data
      - ./certs/redis-tls:/etc/redis/tls
    healthcheck:
      test: [ "CMD", "/healthcheck.sh"]
      interval: 1s
      timeout: 3s
      retries: 3
    #restart: unless-stopped

networks:
  frontend-net:
    driver: bridge
  internal-net:
    driver: bridge


