x-common-env: &common-env
  SSL: "false"
  API_KEY: "s3cr3t"

services:
  frontend-1:
    networks:
      - frontend-net
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server-1
      - server-2
  frontend-2:
    networks:
      - frontend-net
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server-1
      - server-2
  server-1:
    networks:
      - internal-net
      - frontend-net
    environment:
      <<: *common-env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
  server-2:
    networks:
      - internal-net
      - frontend-net
    environment:
      <<: *common-env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
  nginx:
    image: nginx:latest
    networks:
      - frontend-net
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server-1
      - server-2
      - frontend-1
      - frontend-2
  redis:
    environment:
      <<: *common-env
    image: local-redis-alpine
    ports:
      - "6379:6379"
    networks:
      - internal-net
    volumes:
      - ./redis_data:/data
      - ./redis-tls:/etc/redis/tls
    healthcheck:
      test: [ "CMD", "sh", "-c", "redis-cli --tls --cacert /etc/redis/tls/ca.crt ping > /data/redis-healthcheck.log 2>&1 && exit 0 || exit 1" ]
      interval: 1s
      timeout: 3s
      retries: 3
    #restart: unless-stopped

networks:
  frontend-net:
    driver: bridge
  internal-net:
    driver: bridge


