x-common-env: &common-env
  SSL: "true"
  API_KEY: "s3cr3t"

services:
  frontend-1:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server-1
      - server-2
  frontend-2:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server-1
      - server-2
  server-1:
    environment:
      <<: *common-env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
  server-2:
    environment:
      <<: *common-env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server-1
      - server-2
      - frontend-1
      - frontend-2
  redis:
    environment:
      <<: *common-env
    image: local-redis-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./redis-tls:/etc/redis/tls
    healthcheck:
      test: [ "CMD", "sh", "-c", "redis-cli --tls ping --cert /etc/redis/tls/redis.crt --key /etc/redis/tls/redis.key --cacert /etc/redis/tls/ca.crt > /data/redis-healthcheck.log 2>&1 && exit 0 || exit 1" ]
      interval: 1s
      timeout: 3s
      retries: 3
    #restart: unless-stopped
