services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9091:9090"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    #restart: unless-stopped
