apiVersion: v1
kind: Secret
metadata:
  name: common-env-secret
  namespace: appocoord
type: Opaque
stringData:
  SSL: "${SSL_ENABLED}"
  CERT_PATH: "/tls"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  SERVER_NAME: "${SERVER_NAME}"
