apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: appocoord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: frederikuni/nginx-alpine:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: https-certs
              mountPath: /etc/nginx/ssl
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
        - name: https-certs
          hostPath:
            path: /certs/https
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: appocoord
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
    - port: 443
      targetPort: 443
      nodePort: 30443
  selector:
    app: nginx